# Generated by Django 6.0 on 2026-01-12 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DESCRIPTION_COMPLETED', 'Description Completed'), ('DESCRIPTION_FAILED', 'Description Failed'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_FAILED', 'Job Failed'), ('IMAGE_GENERATED', 'Image Generated'), ('SYSTEM', 'System')], help_text='Notification type', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'DescriptionTask', 'ImageTask', 'Job')", max_length=50, null=True)),
                ('related_object_id', models.BigIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (provider, model, etc.)', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'type', '-created_at'], name='notificatio_user_id_3b3832_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
