# Generated by Django 6.0 on 2026-01-12 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f2ad08_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_3b3832_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', 'created_at'], name='notificatio_user_id_fbaa50_idx'),
        ),
    ]
