# Generated by Django 6.0 on 2025-12-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trace_id', models.CharField(help_text='Trace ID for correlating events', max_length=100)),
                ('event_type', models.CharField(choices=[('START', 'Start'), ('PROGRESS', 'Progress'), ('RETRY', 'Retry'), ('ERROR', 'Error'), ('DONE', 'Done'), ('VALIDATION_ERROR', 'Validation Error'), ('EXTERNAL_API_ERROR', 'External API Error'), ('ALGORITHM_ERROR', 'Algorithm Error'), ('RENDER_ERROR', 'Render Error'), ('STORAGE_ERROR', 'Storage Error'), ('AI_PROVIDER_ERROR', 'AI Provider Error')], help_text='Type of event', max_length=50)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Log level', max_length=20)),
                ('message', models.TextField(help_text='Event message')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional event data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='jobs.descriptiontask')),
                ('image_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='jobs.imagetask')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='jobs.job')),
            ],
            options={
                'db_table': 'audit_eventlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='audit_event_job_id_29a0f1_idx'), models.Index(fields=['trace_id'], name='audit_event_trace_i_68e8b6_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_event_event_t_4ac9b7_idx')],
            },
        ),
    ]
