# Generated by Django 6.0 on 2025-12-12 23:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PARTIAL_SUCCESS', 'Partial Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress_total', models.IntegerField(default=0, help_text='Overall progress (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('idempotency_key', models.CharField(blank=True, help_text='Idempotency key for duplicate request prevention', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(help_text='Canonical dataset for this job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='datasets.dataset')),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('algorithm_key', models.CharField(help_text='Algorithm identifier', max_length=100)),
                ('algorithm_version', models.CharField(help_text='Algorithm version', max_length=20)),
                ('params', models.JSONField(default=dict, help_text='Algorithm parameters')),
                ('output_format', models.CharField(choices=[('png', 'PNG'), ('svg', 'SVG'), ('both', 'Both')], default='both', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Task progress (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact_png', models.FileField(blank=True, help_text='PNG artifact file', null=True, upload_to='artifacts/png/')),
                ('artifact_svg', models.FileField(blank=True, help_text='SVG artifact file', null=True, upload_to='artifacts/svg/')),
                ('chart_data', models.JSONField(blank=True, default=dict, help_text='Structured chart data for AI processing', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code if failed', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('trace_id', models.CharField(blank=True, help_text='Trace ID for event correlation', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tasks', to='jobs.job')),
            ],
            options={
                'db_table': 'jobs_imagetask',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DescriptionTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_context', models.TextField(blank=True, help_text='User-provided context for description', null=True)),
                ('provider_used', models.CharField(blank=True, help_text='AI provider used (openai, anthropic, mock)', max_length=50, null=True)),
                ('model_used', models.CharField(blank=True, help_text='AI model used', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Task progress (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('result_text', models.TextField(blank=True, help_text='Generated description text', null=True)),
                ('prompt_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of prompt sent to AI', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code if failed', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('trace_id', models.CharField(blank=True, help_text='Trace ID for event correlation', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_tasks', to='jobs.imagetask')),
            ],
            options={
                'db_table': 'jobs_descriptiontask',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image_task', 'status'], name='jobs_descri_image_t_509371_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='jobs_job_status_277b31_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['dataset', 'created_at'], name='jobs_job_dataset_c3f453_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('created_by', 'idempotency_key'), name='unique_job_idempotency_scoped'),
        ),
        migrations.AddIndex(
            model_name='imagetask',
            index=models.Index(fields=['job', 'status'], name='jobs_imaget_job_id_ffd652_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetask',
            index=models.Index(fields=['algorithm_key', 'algorithm_version'], name='jobs_imaget_algorit_ef3a71_idx'),
        ),
    ]
