# Generated by Django 6.0 on 2026-01-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visualization_config',
            field=models.JSONField(blank=True, default=None, help_text='Visualization settings (color palette, font size, etc.) applied to all charts', null=True),
        ),
    ]
