# Generated by Django 6.0 on 2026-01-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_visualization_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='title',
            field=models.CharField(blank=True, help_text='User-defined title for the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagetask',
            name='user_description',
            field=models.TextField(blank=True, help_text='User-editable description (can be AI-generated then edited)', null=True),
        ),
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Group name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='image_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_imagegroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imagetask',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this image belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='jobs.imagegroup'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for tag display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_tag',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='imagetask',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this image', related_name='images', to='jobs.tag'),
        ),
        migrations.AddIndex(
            model_name='imagetask',
            index=models.Index(fields=['group', 'created_at'], name='jobs_imaget_group_i_66ff3c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegroup',
            index=models.Index(fields=['created_by', 'created_at'], name='jobs_imageg_created_9a1e61_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='jobs_tag_name_95da66_idx'),
        ),
    ]
