# Generated by Django 6.0 on 2026-01-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_imagetask_title_imagetask_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the image is published to the library (draft if False)'),
        ),
        migrations.AddField(
            model_name='imagetask',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the image was published', null=True),
        ),
        migrations.AddIndex(
            model_name='imagetask',
            index=models.Index(fields=['is_published', 'created_at'], name='jobs_imaget_is_publ_6dfbb5_idx'),
        ),
    ]
