# Generated by Django 6.0 on 2026-01-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_is_published_to_imagetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='ai_context',
            field=models.TextField(blank=True, help_text='Context used for AI description generation (stored for reference)', null=True),
        ),
    ]
