# Generated by Django 6.0 on 2026-01-12 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_imagetask_ai_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this image task (inherited from job if not set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='imagetask',
            index=models.Index(fields=['created_by', 'created_at'], name='jobs_imaget_created_35c96e_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetask',
            index=models.Index(fields=['created_by', 'status'], name='jobs_imaget_created_efacb5_idx'),
        ),
    ]
