# Generated by Django 6.0 on 2026-01-12 20:08

from django.db import migrations


def populate_created_by_from_job(apps, schema_editor):
    """
    Data migration: Populate created_by for existing ImageTasks from their job.
    This ensures all existing image tasks have user association for statistics.
    """
    ImageTask = apps.get_model('jobs', 'ImageTask')
    Job = apps.get_model('jobs', 'Job')
    
    # Update ImageTasks that don't have created_by but their job does
    # Use select_related to minimize queries
    image_tasks = ImageTask.objects.filter(created_by__isnull=True).select_related('job')
    
    updated_count = 0
    for image_task in image_tasks:
        if image_task.job and image_task.job.created_by_id:
            image_task.created_by_id = image_task.job.created_by_id
            image_task.save(update_fields=['created_by_id'])
            updated_count += 1
    
    if updated_count > 0:
        print(f"✓ Updated {updated_count} ImageTasks with created_by from their jobs")


def reverse_populate_created_by(apps, schema_editor):
    """
    Reverse migration: Clear created_by (optional, for rollback).
    """
    ImageTask = apps.get_model('jobs', 'ImageTask')
    ImageTask.objects.filter(created_by__isnull=False).update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_imagetask_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_created_by_from_job,
            reverse_populate_created_by,
        ),
    ]
