"""
Visualization configuration for chart generation.

This module provides a centralized, extensible configuration for visual aspects
of all charts generated by the algorithms. Parameters defined here are applied
uniformly across all visualizations.
"""
from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional
from enum import Enum


class FontSize(str, Enum):
    """Font size presets for chart elements."""
    SMALL = "small"
    MEDIUM = "medium"
    LARGE = "large"


class ColorPalette(str, Enum):
    """Predefined color palette options."""
    PROFESSIONAL = "professional"    # Blues and grays - corporate style
    VIBRANT = "vibrant"              # Bright, saturated colors
    EARTH = "earth"                  # Natural, warm tones
    OCEAN = "ocean"                  # Blues and teals
    SUNSET = "sunset"                # Warm oranges and reds
    MONOCHROME = "monochrome"        # Grayscale with accent


# Color palette definitions - each with primary colors for charts
COLOR_PALETTES: Dict[str, Dict[str, Any]] = {
    ColorPalette.PROFESSIONAL.value: {
        "name": "Professional",
        "description": "Corporate style with blues and grays",
        "primary": "#2563eb",           # Blue 600
        "secondary": "#64748b",         # Slate 500
        "accent": "#0891b2",            # Cyan 600
        "colors": [
            "#2563eb", "#3b82f6", "#60a5fa", "#93c5fd",  # Blues
            "#64748b", "#94a3b8", "#cbd5e1",              # Slates
            "#0891b2", "#22d3ee",                          # Cyans
        ],
        "background": "#ffffff",
        "text": "#1e293b",
        "grid": "#e2e8f0",
    },
    ColorPalette.VIBRANT.value: {
        "name": "Vibrant",
        "description": "Bright, saturated colors for impact",
        "primary": "#8b5cf6",           # Violet 500
        "secondary": "#ec4899",         # Pink 500
        "accent": "#f59e0b",            # Amber 500
        "colors": [
            "#8b5cf6", "#a78bfa", "#c4b5fd",  # Violets
            "#ec4899", "#f472b6", "#f9a8d4",  # Pinks
            "#f59e0b", "#fbbf24", "#fcd34d",  # Ambers
            "#10b981", "#34d399",              # Emeralds
        ],
        "background": "#ffffff",
        "text": "#1f2937",
        "grid": "#e5e7eb",
    },
    ColorPalette.EARTH.value: {
        "name": "Earth",
        "description": "Natural, warm tones",
        "primary": "#b45309",           # Amber 700
        "secondary": "#65a30d",         # Lime 600
        "accent": "#0d9488",            # Teal 600
        "colors": [
            "#b45309", "#d97706", "#f59e0b",  # Amber/Orange
            "#65a30d", "#84cc16", "#a3e635",  # Lime/Green
            "#0d9488", "#14b8a6", "#2dd4bf",  # Teal
            "#78716c", "#a8a29e",              # Stone
        ],
        "background": "#fefce8",
        "text": "#422006",
        "grid": "#fef3c7",
    },
    ColorPalette.OCEAN.value: {
        "name": "Ocean",
        "description": "Blues and teals inspired by the sea",
        "primary": "#0284c7",           # Sky 600
        "secondary": "#0891b2",         # Cyan 600
        "accent": "#7c3aed",            # Violet 600
        "colors": [
            "#0284c7", "#0ea5e9", "#38bdf8",  # Sky
            "#0891b2", "#06b6d4", "#22d3ee",  # Cyan
            "#0d9488", "#14b8a6",              # Teal
            "#7c3aed", "#8b5cf6",              # Violet accent
        ],
        "background": "#f0f9ff",
        "text": "#0c4a6e",
        "grid": "#e0f2fe",
    },
    ColorPalette.SUNSET.value: {
        "name": "Sunset",
        "description": "Warm oranges and reds",
        "primary": "#ea580c",           # Orange 600
        "secondary": "#dc2626",         # Red 600
        "accent": "#ca8a04",            # Yellow 600
        "colors": [
            "#ea580c", "#f97316", "#fb923c",  # Orange
            "#dc2626", "#ef4444", "#f87171",  # Red
            "#ca8a04", "#eab308", "#facc15",  # Yellow
            "#be185d", "#ec4899",              # Pink
        ],
        "background": "#fffbeb",
        "text": "#7c2d12",
        "grid": "#fef3c7",
    },
    ColorPalette.MONOCHROME.value: {
        "name": "Monochrome",
        "description": "Elegant grayscale with accent",
        "primary": "#374151",           # Gray 700
        "secondary": "#6b7280",         # Gray 500
        "accent": "#2563eb",            # Blue accent
        "colors": [
            "#111827", "#1f2937", "#374151", "#4b5563",
            "#6b7280", "#9ca3af", "#d1d5db", "#e5e7eb",
            "#2563eb",  # Single accent color
        ],
        "background": "#ffffff",
        "text": "#111827",
        "grid": "#f3f4f6",
    },
}


# Font size configurations
FONT_SIZE_CONFIGS: Dict[str, Dict[str, int]] = {
    FontSize.SMALL.value: {
        "title": 12,
        "axis_label": 10,
        "tick": 8,
        "legend": 8,
        "annotation": 8,
    },
    FontSize.MEDIUM.value: {
        "title": 16,
        "axis_label": 14,
        "tick": 10,
        "legend": 10,
        "annotation": 10,
    },
    FontSize.LARGE.value: {
        "title": 20,
        "axis_label": 16,
        "tick": 12,
        "legend": 12,
        "annotation": 12,
    },
}


@dataclass
class VisualizationConfig:
    """
    Configuration for chart visualization.
    
    This class encapsulates all visual parameters that can be customized
    for chart generation. It is designed to be extensible - new parameters
    can be added without breaking existing algorithms.
    
    Attributes:
        color_palette: The color palette to use (from ColorPalette enum)
        font_size: The font size preset (from FontSize enum)
        custom_params: Additional custom parameters for future extensibility
    """
    color_palette: str = ColorPalette.PROFESSIONAL.value
    font_size: str = FontSize.MEDIUM.value
    custom_params: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate configuration values."""
        if self.color_palette not in COLOR_PALETTES:
            raise ValueError(
                f"Invalid color_palette: {self.color_palette}. "
                f"Valid options: {list(COLOR_PALETTES.keys())}"
            )
        if self.font_size not in FONT_SIZE_CONFIGS:
            raise ValueError(
                f"Invalid font_size: {self.font_size}. "
                f"Valid options: {list(FONT_SIZE_CONFIGS.keys())}"
            )
    
    @classmethod
    def from_dict(cls, data: Optional[Dict[str, Any]]) -> "VisualizationConfig":
        """
        Create a VisualizationConfig from a dictionary.
        
        Args:
            data: Dictionary with configuration values, or None for defaults
            
        Returns:
            VisualizationConfig instance
        """
        if data is None:
            return cls()
        
        return cls(
            color_palette=data.get("color_palette", ColorPalette.PROFESSIONAL.value),
            font_size=data.get("font_size", FontSize.MEDIUM.value),
            custom_params=data.get("custom_params", {}),
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert configuration to dictionary."""
        return {
            "color_palette": self.color_palette,
            "font_size": self.font_size,
            "custom_params": self.custom_params,
        }
    
    def get_palette(self) -> Dict[str, Any]:
        """Get the full color palette configuration."""
        return COLOR_PALETTES[self.color_palette]
    
    def get_colors(self) -> List[str]:
        """Get the list of colors for the selected palette."""
        return COLOR_PALETTES[self.color_palette]["colors"]
    
    def get_primary_color(self) -> str:
        """Get the primary color of the selected palette."""
        return COLOR_PALETTES[self.color_palette]["primary"]
    
    def get_secondary_color(self) -> str:
        """Get the secondary color of the selected palette."""
        return COLOR_PALETTES[self.color_palette]["secondary"]
    
    def get_accent_color(self) -> str:
        """Get the accent color of the selected palette."""
        return COLOR_PALETTES[self.color_palette]["accent"]
    
    def get_background_color(self) -> str:
        """Get the background color of the selected palette."""
        return COLOR_PALETTES[self.color_palette]["background"]
    
    def get_text_color(self) -> str:
        """Get the text color of the selected palette."""
        return COLOR_PALETTES[self.color_palette]["text"]
    
    def get_grid_color(self) -> str:
        """Get the grid color of the selected palette."""
        return COLOR_PALETTES[self.color_palette]["grid"]
    
    def get_font_sizes(self) -> Dict[str, int]:
        """Get the font size configuration."""
        return FONT_SIZE_CONFIGS[self.font_size]
    
    def get_title_fontsize(self) -> int:
        """Get the title font size."""
        return FONT_SIZE_CONFIGS[self.font_size]["title"]
    
    def get_axis_label_fontsize(self) -> int:
        """Get the axis label font size."""
        return FONT_SIZE_CONFIGS[self.font_size]["axis_label"]
    
    def get_tick_fontsize(self) -> int:
        """Get the tick font size."""
        return FONT_SIZE_CONFIGS[self.font_size]["tick"]
    
    def get_legend_fontsize(self) -> int:
        """Get the legend font size."""
        return FONT_SIZE_CONFIGS[self.font_size]["legend"]
    
    def get_annotation_fontsize(self) -> int:
        """Get the annotation font size."""
        return FONT_SIZE_CONFIGS[self.font_size]["annotation"]


# Default configuration for backwards compatibility
DEFAULT_VISUALIZATION_CONFIG = VisualizationConfig()
